### ISSUE TITLE
Switch to codecov CLI

### ISSUE THREAD

**Issue by maleadt** [JuliaCI/julia-coverage-buildkite-plugin#10]
We currently rely on Coverage.jl to submit coverage information to codecov using their API, but (1) Coverage.jl is using an older API that doesn't support org-wide tokens, and (2) IIUC codecov does not support third-party uploaders anymore.

Instead, we should use the official codecov CLI to upload coverage information.

cc @fredrikekre

**Comment by fredrikekre** [comment]
Fixed in #11
